### PR TITLE
Polish translation update v2

### PR DESCRIPTION
**Pull request by lubomsky**
Big commit arrived :muscle:

### CODE REVIEW

**Comment by vassbo** [comment]
Nice! There might be a few other strings you missed. (I counted 15 more) 😉
See this for a comparison: https://github.com/vassbo/freeshow/compare/d306603..cdd9c44#diff-838b2329095aff7bf43b4522c8ad2d2da64c0b89127c90c2b56bd1d54a169c34

**Comment by lubomsky** [comment]
Ouch, that's true. I compared the wrong commit. 
On it's way.

**Comment by lubomsky** [comment]
I believe that's all.
Sorry!

**Comment by vassbo** [comment]
Yep! Thank you! 😊

**Pull request merged**
